name: id3tags
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_rust_bridge: ^1.49.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.erikas.id3tags
        pluginClass: Id3tagsPlugin
      ios:
        pluginClass: Id3tagsPlugin
      linux:
        pluginClass: Id3tagsPlugin
      macos:
        pluginClass: Id3tagsPlugin
      windows:
        pluginClass: Id3tagsPluginCApi