name: audiotags
description: Read and write audio metadata in Flutter. Supports multiple formats.
version: 1.1.1
homepage: https://github.com/erikas-taroza/audiotags
repository: https://github.com/erikas-taroza/audiotags

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1
  flutter_rust_bridge: 1.71.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.erikas.audiotags
        pluginClass: AudiotagsPlugin
      ios:
        pluginClass: AudiotagsPlugin
      linux:
        pluginClass: AudiotagsPlugin
      macos:
        pluginClass: AudiotagsPlugin
      windows:
        pluginClass: AudiotagsPluginCApi
