[package]
name = "audiotags"
version = "1.0.2"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
anyhow = "1.0.68"
flutter_rust_bridge = "1.65.0"
lofty = "0.11.0"
mp4ameta = "0.11.0"

[profile.release]
lto = true