[package]
name = "audiotags"
version = "1.1.3"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
anyhow = "1.0.68"
flutter_rust_bridge = "=1.82.1"
lofty = { git = "https://github.com/Serial-ATA/lofty-rs", rev = "db60766" }

[profile.release]
lto = true
