name: Build & Deploy Rust Libraries

on:
  push:
    branches:
      - master
  workflow_dispatch:
      
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Rust -sys dependencies
        run: |
          sudo apt install libasound2-dev
          sudo apt install libdbus-1-dev pkg-config
          
      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
          
      - name: Build Linux Library
        run: |
          pip install requests
          python ./plugin_tool.py -b linux
          
      - name: Commit
        run: |
          git config --local user.email "erikastaroza@gmail.com"
          git config --local user.name "erikas-taroza"
          git pull
          git add .
          git commit -m "CI: Update Linux libs"
          
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
          
      - name: Build Android Libraries
        run: |
          pip install requests
          python ./plugin_tool.py -b android
          
      - name: Commit
        run: |
          git config --local user.email "erikastaroza@gmail.com"
          git config --local user.name "erikas-taroza"
          git pull
          git add .
          git commit -m "CI: Update Android libs"
          
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
          
      - name: Build Windows Library
        run: |
          pip3 install requests
          python3 .\plugin_tool.py -b windows
          
      - name: Commit
        run: |
          git config --local user.email "erikastaroza@gmail.com"
          git config --local user.name "erikas-taroza"
          git pull
          git add .
          git commit -m "CI: Update Windows libs"
          
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
          
      - name: Build macOS Libraries
        run: |
          pip install requests
          python ./plugin_tool.py -b macos
          
      - name: Commit
        run: |
          git config --local user.email "erikastaroza@gmail.com"
          git config --local user.name "erikas-taroza"
          git pull
          git add .
          git commit -m "CI: Update macOS libs"
          
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
            
      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
            
      - name: Build iOS Libraries
        run: |
          pip install requests
          python ./plugin_tool.py -b ios
          
      - name: Commit
        run: |
          git config --local user.email "erikastaroza@gmail.com"
          git config --local user.name "erikas-taroza"
          git pull
          git add .
          git commit -m "CI: Update iOS libs"
          
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          

  squash:
    runs-on: ubuntu-latest
    needs: [build_linux, build_android, build_windows, build_macos, build_ios]
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --local user.email "erikastaroza@gmail.com"
          git config --local user.name "erikas-taroza"
          git pull
          git reset --soft HEAD~5
          git add .
          git commit -m "CI: Update libraries"
          git push -f
          